# Release
FROM  alpine
# 安装必要的工具包
RUN  apk --update --no-cache add tzdata ca-certificates \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 
    
RUN  apk --no-cache add wget unzip python3 screen bash

RUN mkdir /etc/XrayR
COPY entrypoint.sh /etc/XrayR/entrypoint.sh
# Make the script executable
COPY XrayR /etc/XrayR/XrayR
COPY custom_inbound.json /etc/XrayR/custom_inbound.json
COPY custom_outbound.json /etc/XrayR/custom_outbound.json
COPY dns.json /etc/XrayR/dns.json
COPY route.json /etc/XrayR/route.json
COPY geoip.dat /etc/XrayR/geoip.dat
COPY geosite.dat /etc/XrayR/geosite.dat
COPY rulelist /etc/XrayR/rulelist
COPY config.yml /etc/XrayR/config.yml
COPY cloudflared /etc/XrayR/cloudflared

RUN chmod +x /etc/XrayR/entrypoint.sh
RUN chmod +x /etc/XrayR/XrayR
RUN chmod +x /etc/XrayR/cloudflared
# Set the entrypoint
#ENTRYPOINT ["/etc/XrayR/XrayR"]

CMD ["/bin/bash", "-c", "/etc/XrayR/entrypoint.sh"] 
